def get_last_bot_response(messages):
    """
    Extract the most recent response generated by the bot.

    Supports:
        {"role": "user", "content": "..."}
        {"role": "assistant", "content": "..."}
    """

    for message in reversed(messages):
        if message.get("role") == "assistant":
            return message.get("content", "").strip()

    return None

def is_final_requirement_specification(response):
    if not response:
        return False

    required_sections = [
        "User need:",
        "Problem:",
        "Target users:",
        "Core functionality:",
        "Inputs:",
        "Outputs:",
        "Constraints:",
        "Functional requirements:",
        "Non-functional requirements:",
        "Success criteria:",
    ]

    matches = sum(
        section.lower() in response.lower()
        for section in required_sections
    )

    # Consider it a final specification if most sections are present
    return matches >= 7